### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by Ein-nor** [cerner/jwala#206]
I am only a system administrator and I have no programming experience.

If I follow your building instructions I get the following error message:

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':jwala-webapp:installBabelCli'.
> Process 'command 'C:\Users\Ron\Documents\git\jwala\jwala-webapp\build\nodejs\node-v0.11.10-windows-x64\bin\node.exe''
finished with non-zero exit value 1

I also tried to build jwala on linux an macosx.
Same result

**Comment by jmahmoodcc** [comment]
@ZoeLeah can you try updating your repo now and try again?
